### ISSUE TITLE
显示连接超时

### ISSUE THREAD

**Issue by xinyue** [ohsc/dnspod-ddns#9]
pi@RaspberryPi: ~$ sudo dnspod-ddns --dns-domain chunchu.cn --dns-host blog --user xxxx@qq.com --passwd xxxxx
[2014-11-08 20:43:03.002] [ERROR] [default] - { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete](net.js:895:19)

而使用DNSPodClientLite则可以正常更新ip，请问一下可能是什么原因呢？

**Comment by 8427003** [comment]
+1
